services:
  api:
    depends_on:
      - database
    container_name: ${DOCKER_REGISTRY-}techchallengeapi
    build:
      context: ./
      dockerfile: src/FIAP.TechChallenge.ByteMeBurger.Api/Dockerfile
      tags:
        - techchallenge/apirestaurante
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 5s
    networks:
      - tech-challenge
    ports:
      - 8080:8080
    environment:
      - MySqlSettings__Server=database
      - MySqlSettings__Database=${MYSQL_DATABASE}
      - MySqlSettings__Port=${MYSQL_PORT}
      - MySqlSettings__UserId=${MYSQL_USERID}
      - MySqlSettings__Password=${MYSQL_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
  
  database:
    container_name: mysql_database
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERID}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - tech-challenge
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 27017:27017

networks:
  tech-challenge:
    driver: bridge