# Copyright (c) 2024, Italo Pessoa (https://github.com/italopessoa)
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

services:
  api:
    depends_on:
      - database
    container_name: restaurant_api
    build:
      context: ./
      dockerfile: src/FIAP.TechChallenge.ByteMeBurger.Api/Dockerfile
      tags:
        - techchallenge/restaurant_api
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 5s
    networks:
      - tech-challenge
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__MySql=Server=database;Database=${MYSQL_DATABASE};Uid=${MYSQL_USERID};Pwd=${MYSQL_PASSWORD};Port=${MYSQL_PORT}
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
  database:
    container_name: restaurant_db
    build:
      context: ./database
      dockerfile: Dockerfile
      tags:
        - techchallenge/restaurant_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERID}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - tech-challenge

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 27017:27017

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - tech-challenge

networks:
  tech-challenge:
    driver: bridge
