apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
    - name: api-container
      image: techchallenge/api
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: configmap-api
