apiVersion: v1
kind: Pod
metadata:
  name: {{ include "techchallenge-db.fullname" . }}
  labels:
    {{- include "techchallenge-db.labels" . | nindent 4 }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: persistent-volume
      ports:
        - containerPort: 80
      env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pod.secretName }}
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pod.secretName }}
              key: MYSQL_USER
      envFrom:
        - configMapRef:
            name: {{ .Values.pod.configmapName }}
  volumes:
    - name: persistent-volume
      persistentVolumeClaim:
        claimName: {{ .Values.pod.pvcName }}
