apiVersion: v1
kind: Service
metadata:
  name: {{ include "techchallenge-db.fullname" . }}
  labels:
    {{- include "techchallenge-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "techchallenge-db.selectorLabels" . | nindent 4 }}