# Copyright (c) 2024, Italo Pessoa (https://github.com/italopessoa)
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-api
  labels:
    app: api
data:
  MySqlSettings__Server: "svc-mysql"
  MySqlSettings__Database: "restaurante2"
  MySqlSettings__Port: "3306"
  ASPNETCORE_ENVIRONMENT: "Development"
  Serilog__WriteTo__2__Args__serverUrl: "http://svc-seq:80"
  Serilog__WriteTo__2__Args__formatter: "Serilog.Formatting.Json.JsonFormatter, Serilog"
  MercadoPago__WebhookSecret: ""


