# Copyright (c) 2024, Italo Pessoa (https://github.com/italopessoa)
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-db
  labels:
    app: mysql-pod
  annotations:
    description: "This is a configmap for mysql-pod"
data:
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_DATABASE: "restaurante2"


