apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: pod-api
      labels:
        app: api
    spec:
      containers:
        - name: container-pod-api
          image: ghcr.io/soat-fiap/fiap.techchallenge.bytemeburger/api:latest
          ports:
            - name: liveness-port
              containerPort: 8080
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: liveness-port
              path: /health
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              port: liveness-port
              path: /health
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 10m
          envFrom:
            - configMapRef:
                name: configmap-api
