apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db
  labels:
    app: pod-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-mysql
  template:
    metadata:
      name: pod-mysql
      labels:
        app: pod-mysql
    spec:
      containers:
        - name: mysql-container
          image: ghcr.io/soat-fiap/fiap.techchallenge.bytemeburger/db:latest
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: MYSQL_USER
          envFrom:
            - configMapRef:
                name: configmap-db
#          resources:
#            requests:
#              cpu: 50m
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-db
