apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: pod-api
      labels:
        app: api
    spec:
      containers:
        - name: container-pod-api
          image: techchallenge/api
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: configmap-api
