# Copyright (c) 2024, Italo Pessoa (https://github.com/italopessoa)
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: ghcr.io/soat-fiap/fiap.techchallenge.bytemeburger/db:latest
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage-class
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: configmap-db
  volumes:
    - name: mysql-persistent-storage-class
      persistentVolumeClaim:
        claimName: pvc-db-slow
