apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: ghcr.io/soat-fiap/fiap.techchallenge.bytemeburger/db:latest
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage-class
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: configmap-db
  volumes:
    - name: mysql-persistent-storage-class
      persistentVolumeClaim:
        claimName: pvc-db-slow
