apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: techchallenge/db
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: MYSQL_USER
      envFrom:
        - configMapRef:
            name: configmap-db
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 15
        periodSeconds: 10
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: pvc-db
