apiVersion: v1
kind: Pod
metadata:
  name: pod-api
  labels:
    app: api
spec:
  containers:
    - name: container-pod-api
      image: techchallenge/api
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: configmap-api
