apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
  labels:
    app: pod-mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
  storageClassName: standard
