apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-seq
  labels:
    app: pod-seq
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/seq
  storageClassName: standard
