apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  labels:
    app: pod-mysql
spec:
  selector:
    matchLabels:
      app: pod-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
