apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-seq
  labels:
    app: pod-seq
spec:
  selector:
    matchLabels:
      app: pod-seq
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
