# Copyright (c) 2024, Italo Pessoa (https://github.com/italopessoa)
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  labels:
    app: mysql-pod
type: Opaque
data:
  MYSQL_USER: "dGVjaGNoYWxsZW5nZQ=="
  MYSQL_PASSWORD: "dGVjaEAxMjM0"
